### ISSUE TITLE
Add AVL Trees in various languages

### ISSUE THREAD

**Issue by salman-bhai** [salman-bhai/DS-Algo-Handbook#65]
The following Data Structure needs to be implemented in the following languages.
- [x] C
- [x] C++
- [x] Python
- [x] Java

Ground rules:
1. Whoever claims the Issue first, **should** send a Pull Request within 24 hours else it'll be assigned to another claimant and further Pull Requests regarding that issue will not be entertained.
2. Pull Requests sent without **claiming** and referencing the Issue will not be entertained.
3. Make sure your Pull Requests have just one commit in them. **Squash** multiple commits into one if you have to.
4. Make sure you put in the **proper folder**. If you do not know where to push the code for the Data Structures, feel free to ask in the comments section below. :smile:

**Comment by BrunoTissei** [comment]
I'll work on the C version.

**Comment by mlterpstra92** [comment]
Hi, I'll work on the python version

**Comment by salman-bhai** [comment]
Go ahead, @mlterpstra92

**Comment by bashtech123** [comment]
i have worked on c #118

**Comment by amanshahi** [comment]
I will implement in java

**Comment by amanshahi** [comment]
I will implement in java
