### ISSUE TITLE
Add README for Sorting Algorithms

### ISSUE THREAD

**Issue by salman-bhai** [salman-bhai/DS-Algo-Handbook#74]
Hey! Looks like you're on your way to your **First Pull Request**. You don't even need to write a single line of code for this!

Welcome to the **Hacktoberfest**! :smile: This is a First-Timer Issue to increase your confidence in the field of Open-Source. All you have to do is send a Pull Request (Click [here](https://github.com/salman-bhai/DA_A_DS/blob/master/CONTRIBUTING.md) to see how to send a Pull Request).

All you have to do is explain the Sorting Algorithms and an appropriate explanation for the same. Just make sure you explain the concepts in the respective Sorting Algorithms.
- [x] Bubble Sort
- [x] Bucket Sort
- [x] Heap Sort
- [x] Insertion Sort
- [x] Merge Sort
- [x] Quick Sort
- [x] Radix Sort
- [x] Selection Sort
- [x] Shell Sort
- [x] Topological Sort
- [x] Tree Sort

Ground rules:
1. Whoever claims the Issue first, **should** send a Pull Request within 24 hours else it'll be assigned to another claimant and further Pull Requests regarding that issue will not be entertained.
2. Pull Requests sent without **claiming** and referencing the Issue will not be entertained.
3. Make sure your Pull Requests have just one commit in them. **Squash** multiple commits into one if you have to.
4. Make sure you put in the **proper folder**. If you do not know where to push the code for the Data Structures, feel free to ask in the comments section below. :smile:  
5. Kindly claim one Sorting Algorithm before moving to another!

**Comment by mlterpstra92** [comment]
Hi, I'd like to claim this one

**Comment by salman-bhai** [comment]
Which Sorting Algorithm, @mlterpstra92 ?

**Comment by Prernajain2** [comment]
hi, I would like to claim selection sort

**Comment by salman-bhai** [comment]
Go ahead people!

**Comment by ShreyaSa** [comment]
Hi @salman-bhai 
I would like to claim Bucket Sort Algorithm. 
Thanks :)

**Comment by salman-bhai** [comment]
Go ahead, @ShreyaSa

**Comment by Arunraj97** [comment]
Hi I would like to claim Merge Sort

**Comment by aryanhimanshu** [comment]
Hi
I would like to claim bubble sort and insertion sort.

**Comment by pranavgoel25** [comment]
I would like to claim for Heap Sort

**Comment by pranavgoel25** [comment]
commit 4c52c72b3a38ee168dd037dfbd4f6d2d94654d84

**Comment by pranavgoel25** [comment]
4c52c72b3a38ee168dd037dfbd4f6d2d94654d84

**Comment by sks9919** [comment]
I would like to claim for Quick sort.

**Comment by bashtech123** [comment]
i would like to claim for selection sort

**Comment by ashwinpathak20** [comment]
i would like to claim radix sort

**Comment by Viditjn** [comment]
I claim for tree sort

**Comment by Bargsteen** [comment]
I would like to claim Bubble sort

**Comment by pprintz** [comment]
I would like to claim heapsort, mergesort, quicksort, bubble or insertion sort !

**Comment by pranavgoel25** [comment]
I would like to claim for Bubble Sort

**Comment by pranavgoel25** [comment]
I would like to claim for Shell Sort

**Comment by Radhikadua123** [comment]
Hey! I would like to claim for insertion sort

**Comment by Radhikadua123** [comment]
Hey! I did insertion sort. Can you please help me where i have to push?Thanks

**Comment by Radhikadua123** [comment]
Hey! Please see commit  #181. Tkanks

**Comment by Radhikadua123** [comment]
Hey! Please see commit #181 .Thanks

**Comment by Radhikadua123** [comment]
Hey! I would like to claim merge sort.

**Comment by Radhikadua123** [comment]
Hey! Please see commit #183 .Thanks

**Comment by Radhikadua123** [comment]
Hey! I would like to claim quick sort.

**Comment by salman-bhai** [comment]
Hey kindly change commit #183 according to how mentioned @Radhikadua123

**Comment by Radhikadua123** [comment]
Hey! Please see commit #186 .

**Comment by g-akash** [comment]
I wish to claim topological sort.

**Comment by akshatgoel** [comment]
Claimed Tree sort since there was no update.
