### ISSUE TITLE
Add README for Graph Algorithms

### ISSUE THREAD

**Issue by salman-bhai** [salman-bhai/DS-Algo-Handbook#76]
Hey! Looks like you're on your way to your **First Pull Request**. You don't even need to write a single line of code for this!

Welcome to the **Hacktoberfest**! :smile: This is a First-Timer Issue to increase your confidence in the field of Open-Source. All you have to do is send a Pull Request (Click [here](https://github.com/salman-bhai/DA_A_DS/blob/master/CONTRIBUTING.md) to see how to send a Pull Request).

All you have to do is explain the Graph Algorithm and an appropriate explanation for the same. Just make sure you explain the concepts in the respective Graph Algorithm! 
- [x] BFS
- [x] DFS
- [x] Dijkstra's Algorithm
- [x] Prim's Algorithm MST
- [x] Kruskal's Algorithm MST
- [x] Floyd Warshall's Algorithm
- [x] Bellman Ford's Algorithm

Ground rules:
1. Whoever claims the Issue first, **should** send a Pull Request within 24 hours else it'll be assigned to another claimant and further Pull Requests regarding that issue will not be entertained.
2. Pull Requests sent without **claiming** and referencing the Issue will not be entertained.
3. Make sure your Pull Requests have just one commit in them. **Squash** multiple commits into one if you have to.
4. Make sure you put in the **proper folder**. If you do not know where to push the code for the Data Structures, feel free to ask in the comments section below. :smile:  
5. Kindly claim one Graph Algorithm before moving to another!

**Comment by amanmehta-maniac** [comment]
I claim to work on this issue.

**Comment by amanmehta-maniac** [comment]
I have updated the README file for BFS. Please review my PR. I will continue in the same way of explanation if this PR looks fine to you. Waiting for your reply. Thanks :)

**Comment by salman-bhai** [comment]
Go ahead for the others @amanmehta-maniac

**Comment by amanmehta-maniac** [comment]
Ok, I'm on it. Can you please assign this issue to me?

**Comment by salman-bhai** [comment]
Just mention what all you are working on is enough!

**Comment by amanmehta-maniac** [comment]
DFS, Dijkstra, Prim's, Kruskal as of now.

**Comment by Ashiiit** [comment]
I am working on README of Kruskal MST.

**Comment by ashish3112** [comment]
Hi I would like to claim for Dijkstra's Algorithm.

**Comment by ashwinpathak20** [comment]
i claim for bellman ford's algorithm

**Comment by ashwinpathak20** [comment]
i am working on readme for floyd-warshall's algorithm

**Comment by Bargsteen** [comment]
I would like to work on the Kruskal's or Prim's - dependent on which one isn't being worked on already. I can do both, if needed :)

**Comment by akshatgoel** [comment]
Taken up Kruskal Algo since there was no update from few days.
